openapi: 3.0.0
info:
  title: Firebase Integrated Express API
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /:
    get:
      summary: Get Hello World message
      responses:
        '200':
          description: Hello World message
  /projects:
    get:
      summary: Retrieve all projects
      responses:
        '200':
          description: List of projects
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    # Define properties of a person object here
                    name:
                      type: string
                    description:
                      type: string
    post:
      summary: Add a new project
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
      responses:
        '200':
          description: Project added successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  project:
                    type: object
        '500':
          description: Error adding project
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  error:
                    type: string
